# OLEFY_BINDADDRESS='127.0.0.1,::1'
# OLEFY_BINDPORT='10050')
# OLEFY_TMPDIR='/tmp'
# OLEFY_PYTHON_PATH='/usr/bin/python3'
# OLEFY_OLEVBA_PATH='/usr/local/bin/olevba3'
# # 10:DEBUG, 20:INFO, 30:WARNING, 40:ERROR, 50:CRITICAL
# OLEFY_LOGLVL=20
# OLEFY_MINLENGTH=500
# OLEFY_DEL_TMP=1
# OLEFY_DEL_TMP_FAILED=1


/usr/bin/python3 /usr/local/bin/olefy.py